### ISSUE TITLE
`No package 'libxml-2.0' found` PHP build error

### ISSUE THREAD

**Issue by aohren** [googleapis/gapic-generator-php#168]
On some build machines, the PHP build is failing with `No package 'libxml-2.0' found`. 

```
Configuring extensions
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking for strtoll... yes
checking for atoll... yes
checking whether to build with LIBXML support... yes
checking for libxml-2.0 >= 2.7.6... no

STDERR: shtool:echo:Warning: unable to determine terminal sequence for bold mode
shtool:echo:Warning: unable to determine terminal sequence for bold mode
configure: error: Package requirements (libxml-2.0 >= 2.7.6) were not met:

No package 'libxml-2.0' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBXML_CFLAGS
and LIBXML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

         and referenced by '@gapic_generator_php//rules_php_gapic:php_gapic_generator_binary'
ERROR: Analysis of target '//google/ads/googleads/v5/ads_assembly:googleads-v5-php-micro-adslib' failed; build aborted: no such package '@php_gapic_generator_composer_install//': no such package '@php_micro//': Traceback (most recent call last):
	File "/tmpfs/tools/bazel_root/9c17b202d88c490a45ea631b0d45ecee/external/gapic_generator_php/rules_php_gapic/php_repo.bzl", line 64
		_execute_and_check_result(ctx, <3 more arguments>)
	File "/tmpfs/tools/bazel_root/9c17b202d88c490a45ea631b0d45ecee/external/gapic_generator_php/rules_php_gapic/php_repo.bzl", line 20, in _execute_and_check_result
		fail(<1 more arguments>)

Failed to execute command: `["./configure", "--enable-static", "--disable-all", "--without-pear", "--enable-phar", "--enable-json", "--enable-filter", "--enable-tokenizer", "--with-libxml", "--enable-xml", "--enable-dom", "--enable-xmlwriter", "--enable-mbstring", "--disable-mbregex", "--with-openssl", "--enable-bcmath", "--prefix=/tmpfs/tools/bazel_root/9c17b202d88c490a45ea631b0d45ecee/external/php_micro"]`
Exit Code: 1
```

**Comment by chrisdunelm** [comment]
@aohren Yes, unfortunately the PHP runtime does rely on some platform libraries being installed. It's not as hermetic as we would like.

Step 3 of https://github.com/googleapis/gapic-generator-php/blob/master/DEVELOPMENT.md states which dependencies are required.
If you can arrange for these dependencies to be present, then all will be well.

**Comment by aohren** [comment]
Ah excellent, thank you I had missed those deps. Will update build machines and close this out once I verify that's got it sorted.

**Comment by aohren** [comment]
Confirmed installing `libxml2-dev` on build machines fixed the issue.
